services:
  musiccollection-frontend:
    image: ghcr.io/alexanderboldt/musiccollection-frontend:0.2.0
    container_name: musiccollection-frontend
    ports:
      - 4200:4200
    networks:
      - musiccollection

networks:
  musiccollection:
    name: musiccollection
    external: true
